### ISSUE TITLE
Error message when running jmvtools::prepare()

### ISSUE THREAD

**Issue by sjentsch** [jamovi/jmvtools#6]
I was trying to use the new option of type Action. When trying to compile (I tried both `jmvtools::prepare()` and `jmvtools::install()`), the following error message was returned.

TypeError: Cannot read properties of undefined (reading 'isOptionControl')
    at isOptionControl (/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/uicompiler.js:600:51)
    at removeMissingOptions (/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/uicompiler.js:207:26)
    at removeMissingOptions (/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/uicompiler.js:205:32)
    at uicompile (/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/uicompiler.js:58:19)
    at /home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/index.js:379:13
    at Object.<anonymous> (/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3/jmvtools/node_modules/jamovi-compiler/index.js:626:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

Cannot read properties of undefined (reading 'isOptionControl')

> installed.packages()[row.names(installed.packages()) == "jmvtools"]
 [1] "jmvtools"                                        
 [2] "/home/sjentsch/R/x86_64-pc-linux-gnu-library/4.3"
 [3] "2.4.6"                                           
 [4] NA                                                
 [5] NA                                                
 [6] "node (>= 1.1), jmvcore (>= 2.3.4)"               
 [7] NA                                                
 [8] NA                                                
 [9] NA                                                
[10] "What license is it under?"                       
[11] NA                                                
[12] NA                                                
[13] NA                                                
[14] NA                                                
[15] "no"                                              
[16] "4.3.1"                                           

jamovi 2.4.2, jmvcore 2.4.2

and the two yaml-files that I changed:
[jtarrangecols.u.yaml.txt](https://github.com/jamovi/jmvtools/files/12215872/jtarrangecols.u.yaml.txt)
[jtarrangecols.a.yaml.txt](https://github.com/jamovi/jmvtools/files/12215873/jtarrangecols.a.yaml.txt)

**Comment by jonathon-love** [comment]
i'm guessing there's something malformed in your yaml, and we're not handling it well.

**Comment by jonathon-love** [comment]
@dropmann

**Comment by dropmann** [comment]
Hi! So in the u.yaml the ctrl type is ActionButton not Action. Action is the data type for the a.yaml. It does surprise me that it didn't give a more helpful error. Maybe it has something to do with Action being valid a data type.
